# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\os_system\tela_teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(595, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(595, 586))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.pb_cadastrar = QtWidgets.QPushButton(Form)
        self.pb_cadastrar.setGeometry(QtCore.QRect(268, 495, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pb_cadastrar.setFont(font)
        self.pb_cadastrar.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pb_cadastrar.setObjectName("pb_cadastrar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 144, 41, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\os_system\\usuario.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 230, 51, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("c:\\os_system\\cadeado.png"))
        self.label_3.setObjectName("label_3")
        self.rb_cpf = QtWidgets.QRadioButton(Form)
        self.rb_cpf.setGeometry(QtCore.QRect(299, 65, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rb_cpf.setFont(font)
        self.rb_cpf.setStyleSheet("color: rgb(255, 255, 255);")
        self.rb_cpf.setObjectName("rb_cpf")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(74, 505, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.le_login = QtWidgets.QLineEdit(Form)
        self.le_login.setGeometry(QtCore.QRect(150, 144, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_login.setFont(font)
        self.le_login.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width: 2px;")
        self.le_login.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_login.setObjectName("le_login")
        self.pb_sair = QtWidgets.QPushButton(Form)
        self.pb_sair.setGeometry(QtCore.QRect(314, 359, 121, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_sair.sizePolicy().hasHeightForWidth())
        self.pb_sair.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pb_sair.setFont(font)
        self.pb_sair.setStyleSheet("background-color: rgb(46, 255, 242);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pb_sair.setObjectName("pb_sair")
        self.pb_login = QtWidgets.QPushButton(Form)
        self.pb_login.setGeometry(QtCore.QRect(104, 359, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pb_login.setFont(font)
        self.pb_login.setStyleSheet("background-color: rgb(46, 255, 242);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 15px;\n"
"border-color: black;")
        self.pb_login.setObjectName("pb_login")
        self.rb_cnpj = QtWidgets.QRadioButton(Form)
        self.rb_cnpj.setGeometry(QtCore.QRect(158, 65, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rb_cnpj.setFont(font)
        self.rb_cnpj.setStyleSheet("color: rgb(255, 255, 255);")
        self.rb_cnpj.setChecked(True)
        self.rb_cnpj.setObjectName("rb_cnpj")
        self.le_senha = QtWidgets.QLineEdit(Form)
        self.le_senha.setGeometry(QtCore.QRect(150, 230, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.le_senha.setFont(font)
        self.le_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width: 2px;")
        self.le_senha.setObjectName("le_senha")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(110, 300, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 127);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setToolTip(_translate("Form", "<html><head/><body><p>thfdghdfg</p></body></html>"))
        self.pb_cadastrar.setText(_translate("Form", "Cadastrar Oficina"))
        self.rb_cpf.setText(_translate("Form", "CPF"))
        self.label.setText(_translate("Form", "Não é cadastrado?"))
        self.le_login.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.le_login.setPlaceholderText(_translate("Form", "Login "))
        self.pb_sair.setText(_translate("Form", "Sair"))
        self.pb_login.setText(_translate("Form", "LOGIN"))
        self.rb_cnpj.setText(_translate("Form", "CNPJ"))
        self.le_senha.setPlaceholderText(_translate("Form", "Senha"))
